# Generated by Django 2.1.3 on 2019-01-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('links_filter', models.TextField(blank=True, null=True)),
                ('related_filter', models.TextField(blank=True, null=True)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets_by_icon', to='images.ImageSource')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets_by_photo', to='images.ImageSource')),
            ],
        ),
    ]
