# Generated by Django 2.1.3 on 2019-01-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='capabilities',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rulesets',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statscatalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statscounters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statsmetadata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statsrelations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statssubscriptions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
