# Generated by Django 2.1.3 on 2019-01-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Use repository')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Subversion')], default=1)),
                ('location', models.CharField(max_length=255, verbose_name='Repository location')),
                ('enable_polling', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('poll_frequency', models.PositiveIntegerField(default=15, verbose_name='Polling frequency in minutes')),
                ('pinger_name', models.CharField(db_index=True, max_length=64)),
                ('forward_pinger_mail', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('project_name', models.CharField(db_index=True, max_length=128)),
                ('default_module_name', models.CharField(max_length=64, null=True)),
                ('path_regexes', models.TextField(null=True, verbose_name='Path regular expressions')),
                ('revision_url', models.CharField(max_length=255, null=True, verbose_name='Revision URL pattern')),
                ('root_url', models.CharField(max_length=255, null=True, verbose_name='Repository root URL')),
                ('uuid', models.CharField(max_length=255, null=True, verbose_name='Repository UUID')),
                ('last_revision', models.PositiveIntegerField(default=0, null=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
