#!/usr/bin/env python
"""
Given a .tar.gz file generated by cia-backup,
extract all messages from the embedded ring buffers.
This will result in each unique message being written
to a file of the form <outputdir>/<hash>.

This is designed to be an easy way to generate a
corpus of real messages for testing new CIA indexing
algorithms.

  usage: extract_messages.py cia-YYYY-MM-DD.tar.gz outputdir

--Micah Dowty <micah@navi.cx>
"""

import sys; sys.path[0] += '/..'
from LibCIA.Stats.Messages import MessageBuffer
import tarfile, os, md5

if len(sys.argv) != 3:
    print __doc__
    sys.exit(1)

archive = tarfile.open(sys.argv[1])
outputDir = sys.argv[2]
try:
    os.makedirs(outputDir)
except OSError:
    pass

for item in archive:
    if item.isfile() and item.name.endswith("/_msg"):
        buffer = MessageBuffer(path="", file=archive.extractfile(item))
        buffer._init()

        for uid, message in buffer.getLatest():
            text = message.toxml().encode("utf-8")
            digest = md5.new(text).hexdigest()
            open(os.path.join(outputDir, digest), "w").write(text)
            print digest
